const events = [
    {key:1,title:"Child Support",img:"https://i.ibb.co/5RLNGvF/Child-Support.png",bgc:"#FFBD3E"},
    {key:2,title:"Refuge shelter",img:"https://i.ibb.co/Zd85Qsc/Refuge-Shelter.png",bgc:"#FF7044"},
    {key:3,title:"Food Charity",img:"https://i.ibb.co/JCdRJLx/Food-Charity.png",bgc:"#3F90FC"},
    {key:4,title:"Host a clothing swap",img:"https://i.ibb.co/KFGZjtF/Clothing-Swap.png",bgc:"#421FCF"},
    {key:5,title:"Host a river clean-up",img:"https://i.ibb.co/h9bNW7j/River-Cleaning.png",bgc:"#3F90FC"},
    {key:6,title:"Clean water for children",img:"https://i.ibb.co/WyZhK6j/Clean-Water.png",bgc:"#421FCF"},
    {key:7,title:"Good education",img:"https://i.ibb.co/wh2Wym6/Good-Education.png",bgc:"#FFBD3E"},
    {key:8,title:"New books for children",img:"https://i.ibb.co/4TGVjG6/New-Books.png",bgc:"#FF7044"},
    {key:9,title:"Host a study group",img:"https://i.ibb.co/fkYfYZg/Study-Group.png",bgc:"#FFBD3E"},
    {key:10,title:"Build birdhouses for your neighbors",img:"https://i.ibb.co/y5Xn9Sh/Bird-House.png",bgc:"#3F90FC"},
    {key:11,title:"Organize books at the library",img:"https://i.ibb.co/GQfwydP/Organize-Books.png",bgc:"#FF7044"},
    {key:12,title:"Give a seminar on driving safety",img:"https://i.ibb.co/ysrSRQ4/Driving-Safety.png",bgc:"#421FCF"},
    {key:13,title:"Give free music lessons",img:"https://i.ibb.co/mJnPsKr/Free-Music.png",bgc:"#421FCF"},
    {key:14,title:"Teach people how to register to vote",img:"https://i.ibb.co/D9BPjJy/Register-Vote.png",bgc:"#FFBD3E"},
    {key:15,title:"Clean up your local park",img:"https://i.ibb.co/9n3x38G/Park-Cleaning.png",bgc:"#3F90FC"},
    {key:16,title:"Give IT help to local adults",img:"https://i.ibb.co/7vtGPVw/It-Help.png",bgc:"#FF7044"},
    {key:17,title:"Foster a shelter animal",img:"https://i.ibb.co/0jZShHs/Animal-Shelter.png",bgc:"#FFBD3E"},
    {key:18,title:"Babysit during PTA meetings",img:"https://i.ibb.co/Z2BqD1Y/Baby-Sitting.png",bgc:"#3F90FC"},
    {key:19,title:"Collect stuffed animals",img:"https://i.ibb.co/dB7Yqzw/Stuffed-Animal.png",bgc:"#FF7044"},
    {key:20,title:"Collect school supplies",img:"https://i.ibb.co/KKYPKPQ/School-Supplies.png",bgc:"#421FCF"},
]
